### 鉴权
GET http://localhost:8081/sso/auth
Accept: application/json
Token: 871138b5458c45f3a6a9b09235bdbde9


### 登录信息
POST http://localhost:8081/sso/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "123456"
}

###
