### 鉴权
GET http://localhost:8081/sso/auth
Accept: application/json
Token: 01d346c96b06496791086f7b2b20ee90


### 登录信息
POST http://localhost:8081/sso/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "123456"
}

###
